import Head from 'next/head';

import React from 'react';
import NavBar from './NavBar';

type LayoutProps = {
  title?: string;
  children: any;
};

const Layout = ({ title, children }: LayoutProps) => {
  return (
    <>
      <Head>
        <title>{(title && `${title} | Doge Coffee`) || 'Doge Coffee'}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='page'>
        <header className='container mx-auto max-w-full lg:max-w-7xl'>
          <NavBar />
        </header>
        <main>{children}</main>
      </div>
    </>
  );
};

export default Layout;
